### ISSUE TITLE
Some issues regarding Revkit 2.2

### ISSUE THREAD

**Issue by HariMohan84** [msoeken/cirkit#13]
There are several issues are arisen during working with revkit, mentioned as follows:
1) How i can get the quantum cost of the circuit synthesised using any algorithm. it is not coming in circuit  stat or using quipper.
2) How can i synthesise a circuit by any algorithm (eg. tbs or any) using any other gates (**any proposed gates**)?
3) How it can club with **Syrec**? Suppose i create a .real file, there is no command to read this file. Where should i put this file in the system?

Please solve the issues, it will be very beneficial to me and my research work.

**Comment by msoeken** [comment]
I assume that you are using the github version of RevKit.

1. Call `ps -c` on a reversible circuit in the store. It shows you *T* count, *T* depth, and number of logical qubits of the circuit. Via the source code you can also enable to show NCV cost, which is often referred to as quantum costs. Since these numbers have not such a strong correlation with physical implementations of quantum computers, I am not showing them in the statistics anymore, but the source code to compute them is still there: https://github.com/msoeken/cirkit/blob/master/addons/cirkit-addon-reversible/src/reversible/utils/costs.cpp#L117

2. Check all synthesis commands that are available in the *Synthesis commands* category when calling `help`. Also check the demo: https://github.com/msoeken/cirkit/blob/master/addons/cirkit-addon-reversible/demo.cs

3. SyReC is not integrated into the public version of RevKit. You can read *real* files with `read_real <filename>` and `<filename>` can be anywhere on your machine.

**Comment by HariMohan84** [comment]
Thanks for your reply, i will get back once i am able to solve the issue
Thanks again for reply in very short time

**Comment by HariMohan84** [comment]
I have gone through the things, some problems are still there.

**Re 1**: The quantum cost not have much correlation with physical implementations of quantum computers but some reviewers demanding for these costs for comparison. Is it good to compare using number of logical qu bits,  _T_ count and _T_ depth. Moreover, i have replaced the source code with the code provided in the link. Still ncv is not there at the output in terminal.

**Re 2**: I have checked all the commands for synthesis. But not getting the exact procedure. How can i synthesise any benchmark (using real or any) using any other gates (proposed gates), other than Toffoli, Fredkin, etc.

**Re 3**: This issue is solved, now i can able to work with real files. I have read two three articles of yours and documentation for Syrec. Is the tool is available for public use? Kindly share any like that provide any help for me in this.

Kindly show me the right direction

**Comment by HariMohan84** [comment]
please solve the issue.

**Comment by msoeken** [comment]
Please recall that RevKit is an open source project. Let me answer your questions:

1. Remove this line: https://github.com/msoeken/cirkit/blob/master/addons/cirkit-addon-reversible/src/reversible/cli/stores.cpp#L82

2. All synthesis approaches synthesize to Toffoli and Fredkin. If you want your own gate library, you have to write your own synthesis algorithms. Take a look into the ones in https://github.com/msoeken/cirkit/tree/master/addons/cirkit-addon-reversible/src/reversible/synthesis to get an idea how to do it. For your own gates, you need to define the gate type in https://github.com/msoeken/cirkit/blob/master/addons/cirkit-addon-reversible/src/reversible/target_tags.hpp and you can add gates to circuits using the functions in https://github.com/msoeken/cirkit/blob/master/addons/cirkit-addon-reversible/src/reversible/functions/add_gates.hpp

3. The SyReC tool is not public.

**Comment by Tony-Xiaotong-Cui** [comment]
Hi, I encounter a problem. Couldnt find -lcirkit_formal_z3 Do you know what's wrong?
