### ISSUE TITLE
Why the positions of dont care values makes a difference

### ISSUE THREAD

**Issue by Tony-Xiaotong-Cui** [msoeken/cirkit#26]
Hi Mathias,
I tried to synthesize using command like embed -b, tbs -b from the following pla files where dont cares have a different position. 
-00 00 
-01 01
-10 11
-11 10
and 
00- 00 
01- 01
10- 11
11- 10
But the synthesized circuits are very different. The second seems very simple while the first is complicate. Can you explain how this happen? When i want to add ancillary or dont care values to functions that are already reversible, how can i avoid this kind of stuff, i.e., to avoid the synthesized circuits to be complicate so that the overhead is small and meanwhile to avoid the dont care or constants in the circuits are directly noticed.

**Comment by msoeken** [comment]
These are two different functions, since the order of inputs and outputs matters. In this case, embedding will determine that one additional output variable is sufficient to make the function reversible. This will be added as third output and therefore linked with the third input line (0101 in the first example). In the second example the new output will align with the don't cares making it an easier function to synthesize.
