### ISSUE TITLE
unable to reproduce the same benchmark on RevLib using Revkit

### ISSUE THREAD

**Issue by fever2052** [msoeken/cirkit#48]
Dear Mathias,

I'm using the benchmark called 3_17 which according to the revkit it is synthesized using Transformation based synthesis technique. I tried the pla format of the same benchmark and after synthesizing it using the tbs command the circuit size was more than twice of the size of the circuit on Revlib. If it is possible please   tell me where I'm going off that this is happening. 
For instance the RevLib benchmar utilizes 6gates to produce the same circuit but when I synthesize it, it become 11 gates. How can I achieve the same circuit using the pla format the circuit?

Thanks.

**Comment by msoeken** [comment]
Hello,

I am not sure how you went from the 3_17_6.pla to the circuit in RevKit. Here is what I did:

    revkit> read_spec -p "7 0 1 3 4 2 6 5"
    revkit> tbs
    revkit> ps -c
    Lines:        3
    Gates:        8
    T-count:      28
    Logic qubits: 4

This gives me a circuit with 8 gates. The permutation corresponds exactly to the specification of the 3_17 function. I am certain that you cannot do better with the default TBS method, since 3_17 was chosen to be a worst-case example for a 3-input function for TBS. 

There are two other ways to get 6 gate circuits. With exact synthesis for positive controlled Toffoli gates you can get a circuit with 6 gates:

    revkit> read_spec -p "7 0 1 3 4 2 6 5"
    revkit> exs
    revkit> ps -c
    Lines:        3
    Gates:        6
    T-count:      14
    Logic qubits: 4

With exact synthesis for mixed controlled Toffoli gates you get a circuit with 4 gates:

    revkit> read_spec -p "7 0 1 3 4 2 6 5"
    revkit> exs -n
    revkit> ps -c
    Lines:        3
    Gates:        4
    T-count:      14
    Logic qubits: 4

With a more modern TBS that allows Fredkin gates you can also get 6 gates:

    revkit> read_spec -p "7 0 1 3 4 2 6 5"
    revkit> tbs -f --fredkin_lookback
    revkit> ps -c
    Lines:        3
    Gates:        6
    T-count:      7
    Logic qubits: 4

Note that the circuits in RevLib come from many different sources, not only RevKit. Also, RevLib has not been updated in a long time, so many results may be outperformed by newer synthesis algorithms.
