### ISSUE TITLE
Error in 'make cirkit' step

### ISSUE THREAD

**Issue by tanim87** [msoeken/cirkit#63]
Hi Dr. Soeken, 
While executing 'make cirkit' command I am receiving the following error? is there any solution to it? 

Thanks in advance.

![error](https://user-images.githubusercontent.com/42817244/46162742-b5e93f80-c24e-11e8-8be3-e14395a9ca7a.png)

**Comment by hriener** [comment]
Hi tanim87,

Your C++ compiler seems to be too old to build `cirkit`.

The C++ header "optional" is support since C++17 (https://en.cppreference.com/w/cpp/utility/optional).

I think, Mathias carefully documented the requirements for building `cirkit`. Have a look: https://cirkit.readthedocs.io/en/latest/installation.html

Best,
Heinz

**Comment by tanim87** [comment]
Hi Heinz,

I really appreciate your prompt response to the issue. I checked and found that all the requirements are in accordance to the documentation. 
Just to mention that I had no issue installing the previous version. Its occurred when I tried to update to Cirkit-3.

Thanks again.

Regards,
Arif

**Comment by msoeken** [comment]
Hi Arif,

thanks for your message. CirKit 3 is a complete rewrite from the previous version and we make use of modern C++17 language features. This allows us to write more succinct code, but also requires sometimes to customize the C++ compiler path.

Best,
Mathias
